sudo: false

language: node_js
node_js:
  - '8'

services:
  - mongodb

install:
  - npm install -g codecov

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - npm ci --no-optional
  - npm run start-with-dash & npm run test-local
  - codecov
